version: '3.4'

services:
  bawbee.api:
    image: bawbee.api
    build:
      context: .
      dockerfile: Bawbee.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000